name: Python application

on: 
  workflow_dispatch:
  jobs:
    printInputs:
      runs-on: cubotto1
      steps:
          - run: |
             echo "Log level: ${{ github.event.inputs.logLevel }}"
             echo "Tags: ${{ github.event.inputs.tags }}"
