name: Manual Trigger
on: [workflow_dispatch]
jobs:
  stage0:
    name: Read Dust
    runs-on: sds011
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      # PYTHON env not available for ARM
      #- name: Set up Python 3.9
      #  uses: actions/setup-python@v2
      #  with:
      #    python-version: 3.9
      - name: Install dependencies
        run: |
          which python
          which pip3
          pip3 install -e .
      - name: Lint with flake8
        run: |
          pysds011 dust
